### ISSUE TITLE
Poc

### ISSUE THREAD

**Issue by Kokiiez** [Parms-Crypto/CUDA-ORE-DUMP#1]
Before troling, blaming and shaming you should give a poc than just an http server

**Comment by Parms-Crypto** [comment]
The read me states bare bones and the reasonings. The mission was to open source the Cuda, linking and keccak routing to the public. No one cares about a mock network setup if they are this level working CUDA, especially coding for GPU settings and tweaks. This is not a production release for whatever you're trying to do, it needs modifications as stated in the readme for your scenario. DEVS can do whatever they want with the code.

I'm not here to hold people's hands and build their projects for them. I show the path and the rest is up to them. 

Your opening is classic toxic behavior I expected from the issues section. Before you all try to put me on blast, just remember I was friendly and you all mocked me and laughed. You created this situation. Be lucky I kept true to the mission of "for everyone" while you did not. In fact, not a single member showed or help anyone with code on multi wallet displays and such. No one helped anyone with jito, in fact the moment someone had code for something it was pure bragging while normal people struggled to mine. Where was their help? Oh, that's right you spent time voting and pumping up raising difficulty while the code was and still is riddled with bugs. 

Whats your solution to GPU now with your difficulty plans? You going to raise GPU out and kill all small miners on web and mobile? You're at a crossroads and it's only a matter of time before people intialize the Cuda into their setups.

Once ORE v 2 drops than the cooking really begins. 

Also before any other naysayers come and talk trash. Just remember this work is being provided free of charge to the real miner community against a mutable contract by a larper that has no clue what they are doing. In fact unless you have dropped code for the people for free your opinions mean nothing here.

**Comment by Kokiiez** [comment]
I agree with you on this point, the developer doesn't know how to code and doesn't know what he's doing, the discord is terrible. 

As for me, I've been everyone, I've tried to develloper the JITO version, and the 5 bundle version too.

Take a look at https://twitter.com/shoucccc

**Comment by Parms-Crypto** [comment]
I did see your post and did congratulate and mention the timing as being suspicious to dropping. So a pro and a con. 

I do appreciate you open sourcing and respecting the value of the mission "fair and open to all" 

As far as the psyops and blue twitter games, myself along with a lot of miners don't play those games. Can see on nearly any reputable mining forum, a majority of miners don't support meme tokens or any of these games.

If $ore truly wants a chance and hold true to their word. Fun and open to all. Lowest difficulty and throw away the keys. Having this level of centralization by someone that flip flops on a whim and spreads misinformation will not gain miner support. It's pure market manipulation. 

This is all on top wasting electricity, degrading hardware, burning up hardware, etc.. etc.. for what? There is no consensus mechanism, there is no worry about sybil. It's all a game to frontrun code and adjust the mutable contract to keep them having an edge.

Tracking the money on the first vote were traders and market makers deciding decisions for miners. Than spreading misinformation because they assumed are in heavy financially with the market games.

Even to this day hardhatchad keeps blaming his bad code errors on priority fees. Having users blow sol for no reason. Maybe it's on purpose so he can drop miners that are no longer profitable the pysops running deep already with this crew.

Sorry for the rant, sorry if my bluntness discredits your work. You had a good win and did the right thing open sourcing. I'm just heavily guarded after the games and abundance of death threats the moment I open-sourced code. You open source your work, than you have my respect.

**Comment by Kokiiez** [comment]
No worries, I agree with you, personally it doesn't bother me, I've never managed to make much money on the solana channel, everyone forgets it's a scam channel, people create rug tokens, steal the money and do it all over again.
